### PR TITLE
Add support for `hvac_action` template

### PR DESCRIPTION
**Pull request by laszlojakab**
### Description
This PR adds support for HVAC action template. For more details see: https://developers.home-assistant.io/docs/core/entity/climate/#hvac-action

Fixes: #22

### CODE REVIEW

**Comment by sbasmanov** [comment]
Amazing. I did absolutely same thing at same time (today) :) Just wanted to have nice picture in HomeKit.
Also, would be nice to add unique_id as well.

**Comment by laszlojakab** [comment]
> Amazing. I did absolutely same thing at same time (today) :) Just wanted to have nice picture in HomeKit. Also, would be nice to add unique_id as well.

I could add the `unique_id` in a separate PR after this one is merged. Probably the config entry ID would be ok for that: https://developers.home-assistant.io/docs/entity_registry_index/#unique-id-of-last-resort

**Comment by sbasmanov** [comment]
That's funny. Someone created FR for unique_id :)
https://github.com/jcwillox/hass-template-climate/issues/25
I hope Your PR will be accepted, as it really useful feature, especially in HomeKit.

**Comment by laszlojakab** [comment]
@jcwillox could you please check this PR?

**Comment by jcwillox** [comment]
Thanks for adding this! I just started a new job so I've been neglecting my GitHub projects a bit 😁

**Pull request merged**
